# 线上配置文件
# @author lacy
server:
  port: 8202
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
 # Elasticsearch 配置
  elasticsearch:
    uris:
    username:
    password:
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
